### ISSUE TITLE
Copy PuppetLintNpp.dll

### ISSUE THREAD

**Issue by BarnumD** [opticyclic/npp-puppet-lint#1]
Instructions say 'copy PuppetLintNpp.dll' - From where?  How does one obtain this dll?  (I'm hoping you don't say compile it from the source.)

**Comment by opticyclic** [comment]
Oops!
I forgot to upload the binary so right now it does mean compile from source :)

I'll compile and upload as soon as I can!

**Comment by BarnumD** [comment]
Thanks!

**Comment by opticyclic** [comment]
See release https://github.com/opticyclic/npp-puppet-lint/releases/tag/v0.1 
This is from master although was built a few months ago.
Note: you still need puppet lint installed as the plugin does not embed it.

**Comment by opticyclic** [comment]
FYI: That binary didn't match the source. A correct one has been uploaded at https://github.com/opticyclic/npp-puppet-lint/releases/tag/0.5.0.109-beta
